name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with CMake
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libhidapi-hidraw0 libhidapi-dev

      - name: Configure and build with CMake
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: send_rgb_binary
          path: build/send_rgb
  
  release:
    name: Create GitHub Release (Only for [release] Commits)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create GitHub Release
        if: contains(github.event.head_commit.message, '[release]')
        uses: softprops/action-gh-release@v1
        with:
          files: build/send_rgb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
